cabal-version:      2.4
name:               microhs-self-compile
version:            0.1.0.0
synopsis:           AIHC benchmark: MicroHs compiling itself to C
description:
  The MicroHs compiler, built from the sources of the MicroHs-0.16.0.0
  release vendored under microhs/ (Apache-2.0, see microhs/LICENSE), run on
  those same sources to generate the C version of itself.
license:            NONE
build-type:         Simple

executable microhs-self-compile
  main-is:            Main.hs
  hs-source-dirs:     . microhs/ghc microhs/src
  include-dirs:       microhs/src/runtime
  other-modules:      MicroHs.Abstract
                      MicroHs.Builtin
                      MicroHs.Compile
                      MicroHs.CompileCache
                      MicroHs.Config
                      MicroHs.Deriving
                      MicroHs.Desugar
                      MicroHs.EncodeData
                      MicroHs.Embed
                      MicroHs.Exp
                      MicroHs.ExpPrint
                      MicroHs.Expr
                      MicroHs.FFI
                      MicroHs.Flags
                      MicroHs.Fixity
                      MicroHs.Graph
                      MicroHs.Ident
                      MicroHs.IdentMap
                      MicroHs.IntMap
                      MicroHs.IntSet
                      MicroHs.Interactive
                      MicroHs.Lex
                      MicroHs.List
                      MicroHs.Main
                      MicroHs.Names
                      MicroHs.MakeCArray
                      MicroHs.Package
                      MicroHs.Parse
                      MicroHs.State
                      MicroHs.StateIO
                      MicroHs.SymTab
                      MicroHs.TCMonad
                      MicroHs.Translate
                      MicroHs.TypeCheck
                      MicroHs.Version
                      Text.ParserComb
                      Text.PrettyPrint.HughesPJLite
                      Text.PrettyPrint.HughesPJLiteClass
                      System.Console.SimpleReadline
                      Data.Double
                      Data.Integer
                      PrimTable
                      MHSPrelude
                      System.IO.MD5
                      System.IO.Serialize
                      System.IO.TimeMilli
                      System.IO.Transducers
                      System.Compress
  build-depends:      base, array, bytestring, deepseq, directory, filepath, haskeline, process, text, time
  default-language:   Haskell2010
  default-extensions: ScopedTypeVariables TypeSynonymInstances MultiParamTypeClasses FlexibleInstances FlexibleContexts
